### PR TITLE
fix: add index in every folder

### LINKED ISSUE #44: Provide index file
I suspect the lack of index file creating issue on the usage of the library.
It would be better to add index files in every folder to export the elements of the folder.
And also set this new `dist/index.js` as `main` entrypoint of the lib in the package.json

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix #44 

The lib should work better with this `main: dist/index.js` entry point.

### CODE REVIEW

**Review by ahocevar — COMMENTED** [review]
This won't make a differnce. The package has `"type": "module"` in `package.json`. So you need to build an ES Module version and reference it e.g. with `"module": "dist/LyrxParser.js"` instead of `"main": "dist/LyrxParser.js"`.

`main` points to the CommonJS version, `module` to the ES module version. If you don't provide a CommonJS version, you should not have a `main` entry in `package.json`.

**Comment by ger-benjamin** [comment]
Thanks, I've added the missing `module`, and removed the `main`.
I generally add both (I forget the module this time), because I never know who will need which information. If you have a good source explaining which key is used for what in 2024, and by whom, I'm interested.

Currently, I try to improve this situtation: I've a (a bit too quickly configured) project  https://github.com/ger-benjamin/lyrx-to-sld-tester to test this parser and the sld parser together:
 - If I use `npm link` to use my local version of the lyrx parser: it works.
 - If I use the `npm install` version, it doesn't want to compile (cant find right path, I can debug that by adding `.js` at every path of every files in `node_modules/geostyler-lyrx-parser/dist/` ).
 - If I use the `npm install` version, and then copy paste the content of my project into the node module (the content will be the same as with `npm link`, but without the symlink): same error as in the previous point....

I try to fix that here. But also, adding indexes are a good idea I think.

**Comment by ahocevar** [comment]
@ger-benjamin Easier to write code than to explain - see #46 for changes that should fix your problem, along with an explanation.

A good read on this is https://dev.to/jdedwards3/import-and-export-es-modules-in-node-js-using-typescript-with-babel-compilation-bcg.

**Comment by ger-benjamin** [comment]
Superseded by #46

**Pull request closed without merging**
